blogproject/blog/urls.py
from django.urls import path
from .import views


app_name= 'blog'

urlpatterns = [
    path('',views.landing,name='landing'),
    path('register/',views.register,name='register'),
    path('home/', views.home, name='home'),
    path('about/',views.about,name='about'),
    path('details/<int:pk>/',views.details,name='details'),
    path('contact/',views.contact,name='contact'),
    path('contact/submit/',views.contact_submit,name='contact-submit'),
    path('archives/', views.archives, name='archives'),
    path('popular/', views.popular_posts, name='popular_posts'),
    path('login/',views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('create-post/', views.create_post,name='create-post'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete-post/<int:pk>', views.delete_post, name='delete-post'),
    path('post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('post/<int:post_id>/review/', views.add_review, name='add_review'),

]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blogproject/blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    image = models.ImageField(upload_to='posts/', blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_posts', blank=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ["timestamp"]
        
    def is_archived(self):
        return self.created < (timezone.now() - timezone.timedelta(days=14))
    
    def total_likes(self):
        return self.likes.count()
     
    def is_popular(self):
        return self.likes.count() > 2

class Review(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Review by {self.user.username} on {self.post.title}"
    
    class Meta:
        ordering = ['-created_at']

blogproject/blog/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Post, Review

from django import forms
from django.forms.widgets import PasswordInput, TextInput


#LOGIN A USER
class LoginForm(AuthenticationForm):
    username= forms.CharField(widget=TextInput())
    password= forms.CharField(widget=PasswordInput())
    
#REGISTER/CREATE A USER
class CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','password1','password2']
        
#--Create a post
class CreateRecordForm(forms.ModelForm):
      class Meta:
        model= Post
        fields=['title','body','image']    
        
      def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(CreateRecordForm, self).__init__(*args, **kwargs)
    
      def save(self, commit=True):
        instance = super().save(commit=False)
        if self.user:
           instance.author = self.user
        if commit:
           instance.save()
        return instance     
   
    
#--Update a record
class UpdateRecordForm(forms.ModelForm):
      class Meta:
        model= Post
        fields=['title','body','image']     
        
#--Review a post
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 3, 'class': 'form-control'}),
        }        

blogproject/blog/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Post
from django.http import Http404
from django.utils import timezone
from .forms import LoginForm,CreateUserForm,CreateRecordForm,UpdateRecordForm,ReviewForm
from django.core.mail import send_mail
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate,login
from django.contrib import messages 
from django.contrib.auth.decorators import login_required


# Create your views here.

#THE LANDING PAGE
def landing(request):
  template_name='landing.html'
  return render(request, template_name)



# HOME PAGE
@login_required
def home(request):
    template_name="home.html"
    posts = Post.objects.all().order_by('-created')
    popular_posts = [post for post in posts if post.is_popular()]
    context = {
        'posts': posts,
        'popular_posts': popular_posts
    }
    return render(request, template_name, context)


#ABOUT PAGE
def about(request):
  print()
  return render(request, 'about.html')

#DETAILS PAGE
@login_required
def details(request, pk):
    post = get_object_or_404(Post, id=pk)
    reviews = post.reviews.all().order_by('-created_at')
    
    if request.method == 'POST':
        if 'like_post' in request.POST:
            if request.user in post.likes.all():
                post.likes.remove(request.user)
            else:
                post.likes.add(request.user)
            return redirect('blog:details', pk=post.id)
        
  
        elif 'add_review' in request.POST:
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.post = post
                review.user = request.user
                review.save()
                return redirect('blog:details', pk=post.id)
    else:
        form = ReviewForm()
    
    context = {
        'post': post,
        'reviews': reviews,
        'form': form,
        'user_has_liked': request.user in post.likes.all()
    }
    return render(request, 'details.html', context)
  
  
#CONTACT US PAGE
def contact(request):
  return render(request, 'contact.html')


#CONTACT SUBMISSION PAGE
def contact_submit(request):
    if request.method == 'POST':
        # Get form data
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        thoughts = request.POST.get('thoughts')
        email = request.POST.get('email')
        
        # Prepare email content
        subject = f"New Contact Form Submission from {first_name} {last_name}"
        message = f"""
        From: {first_name} {last_name}
        Email: {email}
        
        Message:
        {thoughts}
        """
        sender_email = email
        recipient_email = 'girltogirl427@gmail.com'  # Your email address
        
        try:
            # Send email
            send_mail(
                subject,
                message,
                sender_email,
                [recipient_email],
                fail_silently=False,
            )
            
            # Notify user of success
            messages.success(request, 'Your message has been sent successfully! We will get back to you soon.')
        except Exception as e:
            # Notify user of error
            messages.error(request, 'There was an error sending your message. Please try again later.')
            # You might want to log this error in production
        
        return redirect('blog:contact')
    
    return redirect('blog:contact')

#ARCHIVED POSTS PAGE
@login_required
def archives(request):
  template_name='archive.html'
  one_week_ago = timezone.now() - timezone.timedelta(days=7)
  
  archived_posts = Post.objects.filter(
        created__lt=one_week_ago
    ).order_by('-created')
    
  context = {
        'archived_posts': archived_posts,
        'title': 'Archived Posts'
    }
  return render(request, template_name, context)

# POPULAR POSTS PAGE
@login_required
def popular_posts(request):
    template_name='popular.html'
    posts = Post.objects.all()
    popular_posts = [post for post in posts if post.is_popular()]
    context = {
        'popular_posts': popular_posts,
        'title': 'Popular Posts'
    }
    return render(request, template_name, context)

#LOGIN A USER

def login(request):
  form=LoginForm()
  template_name = 'login.html'
  if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            messages.success(request, 'You have successfully logged in.')
            return redirect('blog:home')
        messages.error(request, 'Invalid username or password.')
  context={'form':form}
  return render(request, template_name,context)

#USER LOGOUT
def logout(request):
    auth.logout(request)
    
    messages.success(request,"Logout success! See you soon")
  
    return redirect("blog:login")
  
  

#REGISTER A USER
def register(request):
  form=CreateUserForm()
  
  if request.method=='POST':
    form = CreateUserForm(request.POST)
    
    if form.is_valid():
      new_form = form.save(commit=False)
      new_form.is_staff = True
      new_form.save()
      
      messages.success(request, "Account created successfully!")
      return redirect("blog:login")
  
  context ={'form':form}
  return render(request,'register.html',context)

#CREATE A POST
@login_required(login_url='login')
def create_post(request):
  template_name='create.html'
  form=CreateRecordForm()
   
  if request.method=="POST":
     form = CreateRecordForm(request.POST, request.FILES, user=request.user)
     
     if form.is_valid():
       form.save()
       
       
       messages.success(request, "Your blog post was created!")
       return redirect("blog:home")
  else: 
    form= CreateRecordForm(user=request.user)
  context ={'form': form}
  return render(request,template_name, context)  

 #--Update a record
@login_required(login_url='login')
def update(request, pk):
  post = Post.objects.get(id=pk)
  template_name='update.html'
  form = UpdateRecordForm(instance=post)
  
  if request.method=='POST':
    form = UpdateRecordForm(request.POST, request.FILES, instance=post)
    
    if form.is_valid():
      form.save()
      messages.success(request,"Your record was updated successfully!")
      
      return redirect("blog:home")
  context={'form': form}
  return render(request, template_name, context) 


#--Delete Record
@login_required(login_url='login')
def delete_post(request, pk):     
     post= Post.objects.get(id=pk)
     post.delete()
     
     messages.success(request,"Your record was deleted!")
     return redirect("blog:home")
   
#--Like a POST
@login_required
def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.likes.all():
        post.likes.remove(request.user)  
    else:
        post.likes.add(request.user)  
    return redirect('details', post_id=post.id)   
  
#--Review a Post
@login_required
def add_review(request, post_id):
  template_name='details.html'
  post = get_object_or_404(Post, id=post_id)
  if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.post = post
            review.user = request.user
            review.save()
            return redirect('blog:details', post_id=post.id)
  else:
        form = ReviewForm()
  return render(request, template_name, {'form': form})

blogproject/blog/templates/contact.html
{% extends "index.html" %}

<title>Girl-{% block title %}Contact Us{% endblock %}</title>

{%block content%}
<div class="container">
<h3>
    Hey Girlie!
</h3>

<h5>
    You're a gem! ✨  Share your love for our authors here. 
    We're thrilled to hear from you!  
    Drop your details below and let's chat
</h5>

<form method="POST" action="{% url 'blog:contact-submit' %}">
    {% csrf_token %}
    <fieldset>
        <legend>Send through your thoughts</legend>
        
        <div>
            <label for="first_name" class="form-label mt-4"></label>
            <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter your first name" required>
        </div>
        
        <div>
            <label for="last_name" class="form-label mt-4"></label>
            <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter last name" required>
        </div>
        
        <div>
            <label for="thoughts" class="form-label mt-4"></label>
            <textarea class="form-control" id="thoughts" name="thoughts" rows="3" placeholder="Your thoughts" required></textarea>
        </div>
        
        <div>
            <label for="email" class="form-label mt-4"></label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required>
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else. Thanks for reaching out queen!</small>
        </div>
        
        <div class="mt-4 text-end">  
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </fieldset>
</form>
</div>
{%endblock%}

blogproject/blog/templates/footer.html
<footer class="footer-section" style="background: linear-gradient(135deg, #ffd6e7 0%, #ffc0cb 100%); padding: 2rem 0; margin-top: auto;">
    <div class="container" >
        <div class="row">
            <!-- About Column -->
            <div class="col-md-4 mb-4">
                <h5 class="footer-heading" style="color: #d23c77; font-family: 'Playfair Display', serif; margin-bottom: 1.5rem;">
                    <i class="fas fa-crown me-2"></i> GirlToGirl
                </h5>
                <p style="color: #555; line-height: 1.7;">
                    Your digital sisterhood where real talk meets real support. 
                    A safe space to share, connect, and grow with your virtual besties.
                </p>
                <div class="social-icons mt-3">
                    <a href="#" class="text-decoration-none me-3" style="color: #ff6b9d; font-size: 1.3rem;">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="#" class="text-decoration-none me-3" style="color: #ff6b9d; font-size: 1.3rem;">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="#" class="text-decoration-none me-3" style="color: #ff6b9d; font-size: 1.3rem;">
                        <i class="fab fa-pinterest"></i>
                    </a>
                </div>
            </div>

            <!-- Quick Links Column -->
            <div class="col-md-2 mb-4">
                <h5 class="footer-heading" style="color: #d23c77; font-family: 'Playfair Display', serif; margin-bottom: 1.5rem;">
                    Quick Links
                </h5>
                <ul class="list-unstyled">
                    <li class="mb-2">
                        <a href="{% url 'blog:home' %}" class="text-decoration-none" style="color: #555; transition: all 0.3s;">
                            <i class="fas fa-chevron-right me-2" style="color: #ff6b9d;"></i> Home
                        </a>
                    </li>
                    <li class="mb-2">
                        <a href="{% url 'blog:popular_posts' %}" class="text-decoration-none" style="color: #555; transition: all 0.3s;">
                            <i class="fas fa-chevron-right me-2" style="color: #ff6b9d;"></i> Popular
                        </a>
                    </li>
                    <li class="mb-2">
                        <a href="{% url 'blog:archives' %}" class="text-decoration-none" style="color: #555; transition: all 0.3s;">
                            <i class="fas fa-chevron-right me-2" style="color: #ff6b9d;"></i> Archives
                        </a>
                    </li>
                    <li class="mb-2">
                        <a href="{% url 'blog:about' %}" class="text-decoration-none" style="color: #555; transition: all 0.3s;">
                            <i class="fas fa-chevron-right me-2" style="color: #ff6b9d;"></i> About
                        </a>
                    </li>
                </ul>
            </div>

            <!-- Contact Column -->
            <div class="col-md-4 mb-4">
                <h5 class="footer-heading" style="color: #d23c77; font-family: 'Playfair Display', serif; margin-bottom: 1.5rem;">
                    Contact Us
                </h5>
                <ul class="list-unstyled">
                    <li class="mb-3 d-flex align-items-start">
                        <i class="fas fa-envelope mt-1 me-3" style="color: #ff6b9d;"></i>
                        <span style="color: #555;">hello@girltogirl.com</span>
                    </li>
                    <li class="mb-3 d-flex align-items-start">
                        <i class="fas fa-phone-alt mt-1 me-3" style="color: #ff6b9d;"></i>
                        <span style="color: #555;">+263 7784117098</span>
                    </li>
                    <li class="d-flex align-items-start">
                        <i class="fas fa-map-marker-alt mt-1 me-3" style="color: #ff6b9d;"></i>
                        <span style="color: #555;">123 Sisterhood Ave<br>Girls Town, GT 12345</span>
                    </li>
                </ul>
            </div>

            <!-- Newsletter Column -->
            <div class="col-md-2 mb-4">
                <h5 class="footer-heading" style="color: #d23c77; font-family: 'Playfair Display', serif; margin-bottom: 1.5rem;">
                    Newsletter
                </h5>
                <p style="color: #555; line-height: 1.7;">
                    Join our sisterhood! Get the latest posts and updates delivered to your inbox.
                </p>
                <form class="mt-3">
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" placeholder="Your email" style="border-color: #ffb6c1;">
                        <button class="btn" type="submit" style="background-color: #ff6b9d; color: white;">
                            <i class="fas fa-paper-plane"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <hr style="border-top: 1px solid rgba(255,255,255,0.3); margin: 2rem 0;">

        <div class="row">
            <div class="col-md-6 text-center text-md-start">
                <p class="mb-0" style="color: #555;">
                    &copy; {% now "Y" %} GirlToGirl. All rights reserved.
                </p>
            </div>
            <div class="col-md-6 text-center text-md-end">
                <a href="#" class="text-decoration-none me-3" style="color: #555;">Privacy Policy</a>
                <a href="#" class="text-decoration-none me-3" style="color: #555;">Terms of Service</a>
                <a href="#" class="text-decoration-none" style="color: #555;">Cookie Policy</a>
            </div>
        </div>
    </div>
</footer>

<style>
    .footer-section a:hover {
        color: #d23c77 !important;
        transform: translateX(3px);
    }
    
    .social-icons a:hover {
        transform: translateY(-3px);
        color: #d23c77 !important;
    }
    
    .input-group button:hover {
        background-color: #d23c77 !important;
    }
    
    .footer-heading {
        position: relative;
        padding-bottom: 10px;
    }
    
    .footer-heading::after {
        content: '';
        position: absolute;
        left: 0;
        bottom: 0;
        width: 50px;
        height: 2px;
        background: linear-gradient(to right, #ff6b9d, #b19cd9);
    }
</style>

blogproject/blog/templates/landing.html
{% extends "index.html" %}

{% block content %}

<style>
    .landing-hero {
        background: linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%);
        min-height: 100vh;
        margin-top:-25px;
        display: flex;
        align-items: center;
        position: relative;
        overflow: hidden;
    }
    
    .landing-content {
        z-index: 2;
        position: relative;
    }
    
    .floating-hearts {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        overflow: hidden;
        z-index: 1;
    }
    
    .heart {
        position: absolute;
        display: block;
        width: 20px;
        height: 20px;
        background: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%23ffffff80'><path d='M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z'/></svg>") no-repeat center center;
        background-size: contain;
        animation: float 15s linear infinite;
        opacity: 0.6;
    }
    
    @keyframes float {
        0% {
            transform: translateY(100vh) scale(0);
            opacity: 0;
        }
        10% {
            opacity: 0.6;
        }
        100% {
            transform: translateY(-20vh) scale(1.5);
            opacity: 0;
        }
    }
    
    .btn-girly {
        background-color: #ff6b9d;
        border-color: #ff6b9d;
        color: white;
        transition: all 0.3s;
        border-radius: 50px;
        padding: 12px 30px;
        font-weight: 600;
        box-shadow: 0 4px 15px rgba(255, 107, 157, 0.4);
    }
    
    .btn-girly:hover {
        background-color: #ff4785;
        border-color: #ff4785;
        transform: translateY(-3px);
        box-shadow: 0 7px 20px rgba(255, 107, 157, 0.6);
        color: white;
    }
    
    .welcome-text {
        font-size: 1.2rem;
        line-height: 1.8;
        color: #555;
    }
    
    .title {
        font-family: 'Playfair Display', serif;
        font-weight: 700;
        color: #d23c77;
        text-shadow: 2px 2px 4px rgba(0,0,0,0.1);
    }
    
    .subtitle {
        font-family: 'Montserrat', sans-serif;
        font-weight: 300;
        color: #666;
    }
</style>

<div class="landing-hero">
    <!-- Floating hearts background -->
    <div class="floating-hearts" id="hearts-container"></div>
    
    <div class="container landing-content">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h1 class="title display-4 mb-4">👑 Girl-To-Girl Blog 👑</h1>
                
                <div class="welcome-text bg-white p-4 rounded shadow-sm mb-5">
                    <p class="lead mb-4">Hey gorgeous! 💖 Welcome to your digital sisterhood where real talk meets real support.</p>
                    
                    <p>This is your safe space to share, vent, celebrate, and connect with your virtual besties. Whether it's life hacks, relationship advice, or just girl talk - we've got your back, queen!</p>
                </div>
                
                <div class="d-flex flex-column flex-md-row justify-content-center gap-3 mb-4">
                    <a href="{% url 'blog:login' %}" class="btn btn-girly">
                        <i class="fas fa-sign-in-alt me-2"></i> Login to Your Account
                    </a>
                    
                    <a href="{% url 'blog:register' %}" class="btn btn-outline-pink">
                        <i class="fas fa-user-plus me-2"></i> Join the Sisterhood
                    </a>
                </div>
                
                <div class="mt-4">
                    <p class="text-muted">Already feeling the girl power? 👯‍♀️ Dive in, darling!</p>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // Create floating hearts
    document.addEventListener('DOMContentLoaded', function() {
        const container = document.getElementById('hearts-container');
        const heartCount = 15;
        
        for (let i = 0; i < heartCount; i++) {
            const heart = document.createElement('span');
            heart.classList.add('heart');
            
            // Random positioning
            heart.style.left = Math.random() * 100 + '%';
            heart.style.top = Math.random() * 100 + '%';
            
            // Random size
            const size = Math.random() * 20 + 10;
            heart.style.width = size + 'px';
            heart.style.height = size + 'px';
            
            // Random animation duration
            heart.style.animationDuration = 5 + Math.random() * 20 + 's';
            heart.style.animationDelay = Math.random() * 5 + 's';
            
            container.appendChild(heart);
        }
    });
</script>

{% endblock %}
{% comment %} {% extends "index.html" %}

{%block content %}
 
  <body>

    <br>
    <br>
    <div class="text-center">

        <h3>Girl-To-Girl Blog</h3>

        <br>

        <h5>Hey, Girlie welcome to the Girl-To-Girl Blog where us ladies actually have the space our mind. Take it as a space to speak to your virtual besties!</h5>

        <hr>

        <br>

        <p>Login and jump back into reading or writing your blogs, or if you new here you can register and meet your virtual besties. we so excited to meet you !
        </p>

        <br>

        <a class="btn btn-success" type="button" href="{%url 'blog:login'%}">Login to your account here &nbsp; <i class="fa fa-user-plus" aria-hidden="true"></i>
        </a>
        

        <br>


        <h6>Don't have an account yet? Register down here</h6>
        <a class="btn btn-success" type="button" href="{%url 'blog:register'%}">Create your account &nbsp; <i class="fa fa-user-plus" aria-hidden="true"></i>
        </a>


  </body>


{%endblock%} {% endcomment %}

blogproject/blog/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm">
  <div class="container-fluid">
    <!-- Brand with logo -->
    <a class="navbar-brand d-flex align-items-center" href="#">
      <img src="{% static 'assets/images/lipstick.png' %}" alt="GirlToGirl Logo" height="30" class="me-2" style="border-radius:50%; width:50px; height:50px; overflow:hidden;">
      <span class="fw-bold text-dark">GirlToGirl</span>
    </a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarColor01">
      <!-- Left-aligned nav items -->
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'blog:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'blog:archives' %}">Archives</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'blog:popular_posts' %}">Popular Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'blog:about' %}">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'blog:contact' %}">Contact Us</a>
        </li>
      </ul>
      
      <!-- Right-aligned auth link -->
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link text-dark" href="#">Welcome, {{request.user}}</a>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'blog:logout' %}"><i class="fas fa-sign-out-alt me-2"></i>Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'blog:login' %}"><i class="fas fa-sign-in-alt me-2"></i>Login </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<style>
    .navbar {
        padding: 0.8rem 1rem;
    }
    
    .navbar-brand {
        font-size: 1.5rem;
    }
    
    .nav-link {
        font-weight: 500;
        margin: 0 0.5rem;
        position: relative;
    }
    
    .nav-link:after {
        content: '';
        position: absolute;
        width: 0;
        height: 2px;
        bottom: 0;
        left: 0;
        background-color: #ff6b9d;
        transition: width 0.3s ease;
    }
    
    .nav-link:hover:after {
        width: 100%;
    }
    
    .navbar-toggler {
        border: none;
    }
</style>
{% comment %} <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GirlToGirl</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarColor01">
      <ul class="navbar-nav me-auto ">
       
        <li class="nav-item" style="color:black;">
          <a class="nav-link active" href="{%url 'blog:home'%}">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:archives'%}">Archives</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:popular_posts'%}">Popular Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:about' %}">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:contact'%}">Contact Us</a>
        </li>
        
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:logout'%}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:login'%}">Login</a>
        </li>
        {% endif %}
        {% comment %} <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Posts</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Popular Posts</a>
            <a class="dropdown-item" href="#">Author Bio</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"></a>
          </div>
        </li> 
      </ul>
    </div>
  </div>
</nav> {% endcomment %}